<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Brows.Composition" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Brows.Win32.Windows\Brows.Win32.Windows.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="README.md" />
  </ItemGroup>
</Project>
